version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/yambo_db
      - SPRING_DATASOURCE_USERNAME=db_user
      - SPRING_DATASOURCE_PASSWORD=db_password
      - JWT_SECRET=mysecretkey
      - FILE_UPLOAD_DIR=/var/lib/web-yambo-files
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - files:/var/lib/web-yambo-files

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=yambo_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  files:
